### ISSUE TITLE
Should also export a viewing key

### ISSUE THREAD

**Issue by zmanian** [FiloSottile/zcash-mini#1]
The Zcash protocol also has support for view keys. Views keys can determine if a tx has been received but not spend them.

I don't believe there is any support for view keys in the full node wallet yet but we could generate and export a view key that could immediately be imported by a user's full node.

**Comment by FiloSottile** [comment]
Ah wonderful, I thought they didn't exist and wished they did.

Yep, let's add them, and add a mode to input the secret key instead of generating it, to get address/view key from a saved key.
