### ISSUE TITLE
Fatal error on certain phrases

### ISSUE THREAD

**Issue by skironDotNet** [FiloSottile/zcash-mini#13]
try `zcash-mini -mnemonic` with phrase

polar donate street struggle shrimp sugar december absurd thunder dinner help disagree nominee napkin dove jaguar electric carpet donate bamboo size ride popular multiply

you'll get
**[FATAL] Error: invalid key: must be 32 bytes with first 4 bits set to 0**

**Comment by FiloSottile** [comment]
What generated that mnemonic?

**Comment by skironDotNet** [comment]
random from https://iancoleman.io/bip39/ this is the source of all my wallets, and I also contribute to that tool, so I wanted to use my existing phrase (well I have different tool for my priv seed transform to 24 words). And some 24 words do work some does not, so it makes no sense, unless your implementation is lacking some checksum up to bip39 standards

**Comment by FiloSottile** [comment]
The tools expects the key to be a valid Zcash shielded wallet key, which needs to have the top bits cleared, so it's not at all guaranteed to work with a key that you did not generate with this tool.

**Comment by skironDotNet** [comment]
But it generates 24 word, so I was under the impression same algo/standard is use to encode this, you even have bip39 folder in your source, so you were intent to implement it according to standard. Can you review for mistakes?

Option 2: Can you extend the tool to accept 64 byte long seed. So normally you have an opinion to generate random or from mnemonic. Random still must be 256bit so 8 bytes. Can you add an option to provide 64 long hex string as seed? The seed would not be an entropy but the actual see so providing same see should result in same address
