### ISSUE TITLE
zcash-mini hasn't been pushed to the ubuntu store

### ISSUE THREAD

**Issue by elopio** [FiloSottile/zcash-mini#9]
Hello!

A couple of months ago we added the packaging to release this project to the snaps store, in #7. But it hasn't been published there yet. We now have a new service that will take care of the continuous delivery for you, so we hope that the process to get into the store will be even easier now.

Please take a look at https://build.snapcraft.io/ and let me know how it goes. We are in beta, so we are looking for comments from devs about their experience in the site.

pura vida.

**Comment by FiloSottile** [comment]
Hello! Sorry for the delayed response. I did not think it through at the time, but while I agree that the sandboxing model is appropriate, I don't think of zcash-mini as a project for which I have the time to handle versioning, releases, and platform-specific distribution. Sorry for wasting your time!

**Comment by come-maiz** [comment]
Don't worry, I can understand.

We have a community of snapcrafters that maintain snaps in the store that haven't beed adopted by upstream. I still think that zcash-mini would be a great addition to the store, so I have started the process to put it under the snapcrafters care, and made a call for testing: https://forum.snapcraft.io/t/call-for-testing-zcash-mini/3643

For me it won't be a lot of effort to continue maintaining the snap, but if you ever want me to transfer it again, just let me know. I can keep you posted with stats and any feedback we get from Ubuntu users.

pura vida.

**Comment by FiloSottile** [comment]
Thanks for understanding and taking it on! I would be more than happy to receive any feedback you get about it.
